MU-Enigma/Hacktoberfest22

Type_3/Level_1/lavaman_level1_prob5.c++

type 3 level 1 prob 5

---

Type_2/Tic-Tac/SuchirRP_tic_tac/tictactoe.py

Fixed Issues raised when previous pull request was closed.
Requirement: Python

SuchirRP_2_tictactoe_python

---

Type_3/Level_1/SuchirRP_Level1_Prob1.py

*Requirements*: python
*input format*: a positive number is required to denote number of rows in the pascal's triangle

SuchirRP_Type1_Level1_Prob1_Python

---

Type_3/Level_1/README.md

*Type_3 Level_1 Problem2: Happy Number*
**Issue:** The examples for the problem were 12 + 92 = 82, 82 + 22 = 68, 62 + 82 = 100, 12 + 02 + 02 = 1 with constraint 1 <= n <= 231 - 1 when they should have been 1^2 + 9^2 = 82, 8^2 + 2^2 = 68, 6^2 + 8^2 = 100, 1^2 + 0^2 + 0^2 = 1 with constraint 1 <= n <= 2^31 - 1

Fixed error in README.md for Type_3 Level_1 Problem2: Happy Number

---

Type_3/Level_1/vedanshi_type3_lvl1_prob2.c

Vedanshi Type3 LVL1 Prob2

---

Type_3/Level_2/avya_type3_level2_problem4.c

avya_level2_problem4

---

Type_3/Level_2/SuchirRP_Type3_Level2_Problem1_3Sum.py

**Input Format:** Enter a series of integers, seperated by spaces in the same line. Ex:- -1 0 1 2 -1 -4

SuchirRP Type3 Level2 Problem1:3Sum python

---

Type_3/Level_1/swarnim-sawane_Type3_Level1_Problem3_SingleNumber.cpp.cpp

swarnim-sawane_Type3_Level1_Problem3_SingleNumber.cpp

---

Type_3/Level_1/siddharth-1303_TYpe3_Level1_Prob1PascalTriangle.py

**InputFormat:** int number of rows

siddharth-1303 type3 level1 problem1

---

Type_3/Level_1/siddharth-1303_TYpe3_Level1_Prob2HappyNumber.py

siddharth-1303 type3 level1 problem2

---

Type_3/Level_1/siddharth-1303_TYpe3_Level1_Prob3SingleNumber.py

inputformat: comma seperated numbers

siddharth-1303 type 3 level1 prob3

---

Type_3/Level_1/siddharth-1303_TYpe3_Level1_Prob5ReverseProblem.py

siddharth-1303 type3 level1 problem5

---

Type_3/type3prob5.py

Reverts MU-Enigma/Hacktoberfest22#138
After merging, realized file is wrong folder

Revert "uploading type3level1prob5"

---

Type_3/Level_1/srikar_level1_problem3.cpp

level 1 problem 3 solved

---

Type_3/Level_3/swarnim-sawane_Type3_Level3_Problem2_SingleNumber.cpp.cpp

Input format  :
->Input number of elements - n
->elements of array nums
1 <= nums.length <= 105
-104 <= nums[i] <= 104

Wait_a_minute

---

Type_3/Level_1/vana_type3_level1_problem2.c

Happy Number

---

Type_3/Level_3/vana_level3_problem2.c

Type 3 Level 3 Problem 2
Language C

vana_level3_problem2

---

Type_3/Level_1/reuben_type3_level1_problem1.c

pascal's triangle solved.
language C.

reuben_level1_problem1

---

Type_3/Level_1/hound_type3_lvl1_prob2.c++

hound_type3_lvl1_prob2

---

Type_3/Level_1/harshit_problem2_level1.pyt

https://github.com/MU-Enigma/Hacktoberfest22/commit/a4de015ba44bfb5560e448a12505eec46306c511

Solution to type 3, level 1, problem 2

---

Type_3/Level_1/Rohan_Potta_level1_Problem03.cpp

Just solved The Question for the Hacktoberfest22

Rohan Potta_Type 3_Level 1_Problem 3

---

Type_3/Level_1/SaiAnish_Level_1_prob_5.cpp

Solved problem_5 level_1 type_3

---

Type_3/Level_2/thames_type3_lvl2_prob3.c++

 thames_type3_lvl2_prob3.c++

---

Type_3/Level_2/thames_type3_lvl2_prob2.c++

 thames_type3_lvl2_prob2.c++

---

Type_3/Level_2/Shashank_Type-3_level-2_question3.c

Finished type 3,level 2 problem 3

---

Type_3/Level_1/Aashish_James_level3_P1.py

I tried solving the Pascals triangle problem statement hopefully it is right.

Solved the Pascal's Triangle problem - Vakes

---

Type_3/Level_1/Aashish_James_Level1_P3.py

Hey I solved the Single Number problem, using a O(n) approach and having a constant space complexity.

Solved the Single Number Problem which is problem 3 in Level 1

---

Type_3/Level_3/SaiAnish_Level_3_prob_2.cpp

can be solved with merge sort O(n*logn) during the merge part but debugging the code.

Solved Type_3 Level_3 Problem_2

---

Type_3/Level_1/vana_type3_level1_problem5.c

Problem 5 - Reverse String
Language - C

vana_type3_level1_problem5.c

---

Type_3/Level_1/atharva_type_lvl1_prob5.py

atharva_type_lvl1_prob5

---

Type_3/Level_1/atharva_type3_lvl1_prob2.py

atharva_type3_lvl1_prob2

---

Type_3/Level_3/thames_type3_lvl3_prob2.c++

thames_type3_lvl3_prob2

---

Type_3/Level_1/atharva_type3_lvl1_prob1.py

atharva_type3_lvl1_prob1

---

Type_3/Level_1/atharva_type3_lvl1_prob4.py

atharva_type3_lvl1_prob4

---

Type_3/Level_3/ravi_problem2.py

- solved type 3 level 3 problem 2.
- hope this gets accepted.

Solved type 3 level 3 problem 2

---

Type_3/Level_2/ravi_problem3.py

- Solved type 3 level 2 problem 3
- Hope this helps the repo

Solved type 3 level 2 problem 3

---

Type_3/Level_1/ravi_problem5.py

- solved type level 1 problem 5

solved type 3 level 1 problem 5
